// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZVxsm0G2JJckryKgMseAsvteKOGxUly8',
    appId: '1:1046136703618:web:b0b96b54d410b618d7029b',
    messagingSenderId: '1046136703618',
    projectId: 'money-tracker-app-fc604',
    authDomain: 'money-tracker-app-fc604.firebaseapp.com',
    storageBucket: 'money-tracker-app-fc604.firebasestorage.app',
    measurementId: 'G-290880GY62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHeXZUB-h9SCxHdrtTWA1hG5i5Uknoriw',
    appId: '1:1046136703618:android:d9af6c813392d8a4d7029b',
    messagingSenderId: '1046136703618',
    projectId: 'money-tracker-app-fc604',
    storageBucket: 'money-tracker-app-fc604.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAcOnEa6Fbpo8Oy5WwU0q6iNucTbgHGOI',
    appId: '1:1046136703618:ios:b7e2235244b77fe1d7029b',
    messagingSenderId: '1046136703618',
    projectId: 'money-tracker-app-fc604',
    storageBucket: 'money-tracker-app-fc604.firebasestorage.app',
    iosBundleId: 'com.example.moneyTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAcOnEa6Fbpo8Oy5WwU0q6iNucTbgHGOI',
    appId: '1:1046136703618:ios:b7e2235244b77fe1d7029b',
    messagingSenderId: '1046136703618',
    projectId: 'money-tracker-app-fc604',
    storageBucket: 'money-tracker-app-fc604.firebasestorage.app',
    iosBundleId: 'com.example.moneyTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZVxsm0G2JJckryKgMseAsvteKOGxUly8',
    appId: '1:1046136703618:web:a3b7f101792e464fd7029b',
    messagingSenderId: '1046136703618',
    projectId: 'money-tracker-app-fc604',
    authDomain: 'money-tracker-app-fc604.firebaseapp.com',
    storageBucket: 'money-tracker-app-fc604.firebasestorage.app',
    measurementId: 'G-S3Z72Q4N2P',
  );
}
